version: '3.1'
services:
  terraform:
    image: simple-ml-pipeline/terraform
    build:
      context: ./infra/terraform
      dockerfile: Dockerfile
    env_file:
      - .env
    command: ["terraform", "apply", "-auto-approve"]
    